# Generated by Django 2.2 on 2021-03-09 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLogsBreakModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='this is types of break defined by the admin', max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('admin_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('total_works_hours', models.CharField(blank=True, max_length=300, null=True)),
                ('total_break_time', models.CharField(blank=True, max_length=300, null=True)),
                ('user_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLogsDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_image', models.FileField(null=True, upload_to='work_log_images')),
                ('address', models.CharField(help_text='this is current address of work log', max_length=300, null=True)),
                ('longitude', models.FloatField(help_text='this is current latitude of work log', null=True)),
                ('latitude', models.FloatField(help_text='this is current longitute of work log', null=True)),
                ('worklog_type', models.CharField(blank=True, choices=[(1, 'CLOCK_IN'), (2, 'CLOCK_OUT'), (3, 'BREAK_IN'), (4, 'BREAK_OUT')], default=1, help_text='clock in type', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('work_log_break_id', models.ForeignKey(help_text='model for the work logs break', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkLogsBreakModel.id+', to='adminside.WorkLogsBreakModel')),
                ('worklog_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkLogsModel.id+', to='adminside.WorkLogsModel')),
            ],
        ),
        migrations.CreateModel(
            name='NoticesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(null=True, upload_to='noticesimage')),
                ('draft', models.BooleanField(default=False, null=True)),
                ('publish', models.BooleanField(default=False, null=True)),
                ('heading', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('admin_id', models.ForeignKey(help_text='admin id will be displayed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
