# Generated by Django 3.1.7 on 2021-03-29 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLogsBreakModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='this is types of break defined by the admin', max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('admin_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('total_works_hours', models.TimeField(blank=True, max_length=300, null=True)),
                ('total_break_time', models.CharField(blank=True, max_length=300, null=True)),
                ('user_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLogsDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_image', models.FileField(null=True, upload_to='work_log_images')),
                ('address', models.CharField(help_text='this is current address of work log', max_length=300, null=True)),
                ('longitude', models.FloatField(help_text='this is current latitude of work log', null=True)),
                ('latitude', models.FloatField(help_text='this is current longitute of work log', null=True)),
                ('worklog_type', models.CharField(blank=True, choices=[(1, 'CLOCK_IN'), (2, 'CLOCK_OUT'), (3, 'BREAK_IN'), (4, 'BREAK_OUT')], default=1, help_text='clock in type', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('work_log_break_id', models.ForeignKey(help_text='model for the work logs break', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkLogsBreakModel.id+', to='adminside.worklogsbreakmodel')),
                ('worklog_id', models.ForeignKey(help_text='model for the work logs details', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkLogsModel.id+', to='adminside.worklogsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TypographyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('h2', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('h3', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('h4', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('bodyText', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(help_text='model for typography', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuspensionEmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(help_text='model for suspension email', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemName', models.CharField(blank=True, max_length=300)),
                ('systemEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('mainColor', models.CharField(blank=True, max_length=300, null=True)),
                ('secondaryColor', models.CharField(blank=True, max_length=300, null=True)),
                ('mainTextColor', models.CharField(blank=True, max_length=300, null=True)),
                ('systemLogo', models.FileField(null=True, upload_to='style_images')),
                ('systemIcon', models.FileField(null=True, upload_to='style_images')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(help_text='model for styling model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterEmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(help_text='model for register email', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(null=True, upload_to='noticesimage')),
                ('draft', models.BooleanField(default=False, null=True)),
                ('publish', models.BooleanField(default=False, null=True)),
                ('heading', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('admin_id', models.ForeignKey(help_text='admin notices', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminEmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtpHostName', models.CharField(max_length=300, null=True)),
                ('smtpPort', models.CharField(max_length=2000, null=True)),
                ('smtpUser', models.CharField(max_length=300, null=True)),
                ('smtpPassword', models.CharField(max_length=2000, null=True)),
                ('smtpAddress', models.CharField(max_length=2000, null=True)),
                ('fromName', models.CharField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
