# Generated by Django 2.2 on 2021-03-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesmodel',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
