# Generated by Django 2.2 on 2021-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_auto_20210309_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticesmodel',
            name='date',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
