# Generated by Django 2.2 on 2021-03-12 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminside', '0003_noticesmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(blank=True, max_length=300)),
                ('system_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('main_color', models.CharField(blank=True, max_length=300, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=300, null=True)),
                ('main_text_color', models.CharField(blank=True, max_length=300, null=True)),
                ('system_logo', models.FileField(null=True, upload_to='style_images')),
                ('system_icon', models.FileField(null=True, upload_to='style_images')),
                ('admin_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
