# Generated by Django 2.2 on 2021-03-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_stylemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylemodel',
            old_name='main_color',
            new_name='mainColor',
        ),
        migrations.RenameField(
            model_name='stylemodel',
            old_name='main_text_color',
            new_name='mainTextColor',
        ),
        migrations.RenameField(
            model_name='stylemodel',
            old_name='secondary_color',
            new_name='secondaryColor',
        ),
        migrations.RenameField(
            model_name='stylemodel',
            old_name='system_email',
            new_name='systemEmail',
        ),
        migrations.RenameField(
            model_name='stylemodel',
            old_name='system_icon',
            new_name='systemIcon',
        ),
        migrations.RenameField(
            model_name='stylemodel',
            old_name='system_logo',
            new_name='systemLogo',
        ),
        migrations.RenameField(
            model_name='stylemodel',
            old_name='system_name',
            new_name='systemName',
        ),
        migrations.RenameField(
            model_name='stylemodel',
            old_name='admin_id',
            new_name='user_id',
        ),
    ]
