# Generated by Django 2.2 on 2021-03-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_auto_20210312_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylemodel',
            old_name='user_id',
            new_name='admin_id',
        ),
    ]
