# Generated by Django 2.2 on 2021-03-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminside', '0006_auto_20210312_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypographyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('h2', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('h3', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('h4', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('bodyText', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('admin_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
