# Generated by Django 2.2 on 2021-03-12 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_typographymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylemodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stylemodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typographymodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='typographymodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
