# Generated by Django 2.2 on 2021-03-02 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLogsBreakModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='this is types of break defined by the admin', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worklog_type', models.IntegerField(default=1)),
                ('captured_image', models.ImageField(null=True, upload_to='work_log_images')),
                ('address', models.CharField(help_text='this is current address of work log', max_length=300, null=True)),
                ('longitude', models.FloatField(help_text='this is current latitude of work log', null=True)),
                ('latitude', models.FloatField(help_text='this is current longitute of work log', null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL)),
                ('work_log_break_id', models.ForeignKey(help_text='model for the work logs break', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkLogsBreakModel.id+', to='adminside.WorkLogsBreakModel')),
            ],
        ),
    ]
