# Generated by Django 2.2 on 2021-03-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklogsmodel',
            old_name='worklog_type',
            new_name='worklog',
        ),
    ]
