# Generated by Django 2.2 on 2021-03-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_auto_20210302_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklogsmodel',
            old_name='worklog',
            new_name='worklog_type',
        ),
    ]
