# Generated by Django 2.2 on 2021-03-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_auto_20210302_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklogsmodel',
            name='worklog_type',
            field=models.CharField(blank=True, choices=[(1, 'CLOCK_IN'), (1, 'CLOCK_OUT'), (1, 'BREAK_IN'), (1, 'BREAK_OUT')], default=1, help_text='clock in type', max_length=20),
        ),
    ]
