# Generated by Django 2.2 on 2021-03-02 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_auto_20210302_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklogsmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worklogsmodel',
            name='captured_image',
        ),
        migrations.RemoveField(
            model_name='worklogsmodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='worklogsmodel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='worklogsmodel',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='WorkLogsDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_image', models.ImageField(null=True, upload_to='work_log_images')),
                ('address', models.CharField(help_text='this is current address of work log', max_length=300, null=True)),
                ('longitude', models.FloatField(help_text='this is current latitude of work log', null=True)),
                ('latitude', models.FloatField(help_text='this is current longitute of work log', null=True)),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('total_works_hours', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('break_start_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('break_end_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('total_break_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('worklog_id', models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkLogsModel.id+', to='adminside.WorkLogsModel')),
            ],
        ),
    ]
