# Generated by Django 2.2 on 2021-03-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_auto_20210302_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklogsmodel',
            name='work_log_break_id',
        ),
        migrations.AddField(
            model_name='worklogsdetailsmodel',
            name='work_log_break_id',
            field=models.ForeignKey(help_text='model for the work logs break', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkLogsBreakModel.id+', to='adminside.WorkLogsBreakModel'),
        ),
    ]
