# Generated by Django 2.2 on 2021-03-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_auto_20210302_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklogsdetailsmodel',
            name='break_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklogsdetailsmodel',
            name='break_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklogsdetailsmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklogsdetailsmodel',
            name='total_break_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklogsdetailsmodel',
            name='total_works_hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
