# Generated by Django 2.2 on 2021-03-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_auto_20210302_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklogsdetailsmodel',
            name='total_break_time',
        ),
        migrations.RemoveField(
            model_name='worklogsdetailsmodel',
            name='total_works_hours',
        ),
        migrations.RemoveField(
            model_name='worklogsmodel',
            name='worklog_type',
        ),
        migrations.AddField(
            model_name='worklogsdetailsmodel',
            name='worklog_type',
            field=models.CharField(blank=True, choices=[(1, 'CLOCK_IN'), (2, 'CLOCK_OUT'), (3, 'BREAK_IN'), (4, 'BREAK_OUT')], default=1, help_text='clock in type', max_length=20),
        ),
        migrations.AddField(
            model_name='worklogsmodel',
            name='total_break_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklogsmodel',
            name='total_works_hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
