# Generated by Django 2.2 on 2021-03-02 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_auto_20210302_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklogsdetailsmodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='worklogsmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
