# Generated by Django 2.2 on 2021-03-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_auto_20210302_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklogsmodel',
            name='total_break_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='worklogsmodel',
            name='total_works_hours',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
