# Generated by Django 2.2 on 2021-03-02 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_auto_20210302_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogsbreakmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worklogsbreakmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
