# Generated by Django 2.2 on 2021-03-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0016_auto_20210303_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklogsdetailsmodel',
            name='break_end_at',
        ),
        migrations.RemoveField(
            model_name='worklogsdetailsmodel',
            name='break_start_at',
        ),
        migrations.RemoveField(
            model_name='worklogsdetailsmodel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='worklogsdetailsmodel',
            name='total_break_time',
        ),
    ]
