# Generated by Django 2.2 on 2021-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0017_auto_20210303_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogsmodel',
            name='total_break_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
