# Generated by Django 2.2 on 2021-03-03 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0018_worklogsmodel_total_break_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogsdetailsmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
