# Generated by Django 2.2 on 2021-03-04 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminside', '0019_worklogsdetailsmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogsbreakmodel',
            name='admin_id',
            field=models.ForeignKey(help_text='model for the work logs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User.id+', to=settings.AUTH_USER_MODEL),
        ),
    ]
