# Generated by Django 2.2 on 2021-03-04 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0020_worklogsbreakmodel_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogsbreakmodel',
            name='end_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
