# Generated by Django 2.2 on 2021-03-04 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0021_worklogsbreakmodel_end_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklogsbreakmodel',
            name='end_at',
        ),
        migrations.AddField(
            model_name='worklogsmodel',
            name='end_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
