import placeholder from '../../assets/img/placeholder.png'
export const data =[
    {
              id:'1',
              firstName:'marghob',
              secondName:'tar',
              identityNumber:'24243231',
              passport:'2342342',
              gender:'Male',
              dob:'27-11-1996',
              phone:'213142',
              cell:'1213123',
              email:'marghoob@gmail.com',
              address:'Sangla hill dist nankana',
              city:'sangla hill',
              zip:'2D1',
              country:'Pakistan',
              password:'ahmad',
              image:placeholder,
              trainingInstitute:'traingn',
              institutePhone:'phone ',
              facilitatorName:'asif',
              institutioAccount:'acount',
              instituteAddress:'addr',
              instituteCity:'lahore',
              instituteZip:'23e42',
              instituteCountry:'pakistan',
              registerName:'lsjl',
              companyName:"Wantech",
              accountStatus:false
              
            },

            {
                  id:'1',
                  firstName:'Asim',
                  secondName:'tar',
                  identityNumber:'24243231',
                  passport:'2342342',
                  gender:'Male',
                  dob:'11/11/1996',
                  phone:'213142',
                  cell:'1213123',
                  email:'marghoob@gmail.com',
                  address:'Sangla hill dist nankana',
                  city:'sangla hill',
                  zip:'2D1',
                  country:'Pakistan',
                  password:'ahmad',
                  image:placeholder,
                  trainingInstitute:'traingn',
                  institutePhone:'phone ',
                  facilitatorName:'asif',
                  institutioAccount:'acount',
                  instituteAddress:'addr',
                  instituteCity:'lahore',
                  instituteZip:'23e42',
                  instituteCountry:'pakistan',
                  registerName:'lsjl',
                  companyName:"Wantech",
                  accountStatus:false
                  
                },
                {
                  id:'2',
                  firstName:'tarar',
                  secondName:'tar',
                  identityNumber:'24243231',
                  passport:'2342342',
                  gender:'Male',
                  dob:'11/11/1996',
                  phone:'213142',
                  cell:'1213123',
                  email:'marghoob@gmail.com',
                  address:'Sangla hill dist nankana',
                  city:'sangla hill',
                  zip:'2D1',
                  country:'Pakistan',
                  password:'ahmad',
                  image:placeholder,
                  trainingInstitute:'traingn',
                  institutePhone:'phone ',
                  facilitatorName:'asif',
                  institutioAccount:'acount',
                  instituteAddress:'addr',
                  instituteCity:'lahore',
                  instituteZip:'23e42',
                  instituteCountry:'pakistan',
                  registerName:'lsjl',
                  companyName:"Wantech",
                  accountStatus:false
                  
                }
]